# Generated by Django 6.0.4 on 2026-04-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_player_age_player_beach_experience_player_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AddField(
            model_name='court',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон ответственного'),
        ),
    ]
