# Generated by Django 6.0.4 on 2026-05-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournamentgroup_match_group_tournamentpair_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='setresult',
            options={'verbose_name': 'Партия', 'verbose_name_plural': 'Партии'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AlterModelOptions(
            name='tournamentpair',
            options={'verbose_name': 'Пара турнира', 'verbose_name_plural': 'Пары турнира'},
        ),
        migrations.AlterField(
            model_name='court',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название площадки'),
        ),
        migrations.AlterField(
            model_name='match',
            name='bracket_type',
            field=models.CharField(choices=[('main', 'Основная сетка'), ('losers', 'Сетка проигравших'), ('third_place', 'Матч за 3 место')], default='main', max_length=20, verbose_name='Тип сетки'),
        ),
        migrations.AlterField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.court', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(verbose_name='Дата матча'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер матча'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.TimeField(verbose_name='Время матча'),
        ),
        migrations.AlterField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournament.match', verbose_name='Следующий матч'),
        ),
        migrations.AlterField(
            model_name='match',
            name='pair1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pair1', to='tournament.tournamentpair', verbose_name='Пара 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='pair2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pair2', to='tournament.tournamentpair', verbose_name='Пара 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=20, verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('ongoing', 'Идёт'), ('finished', 'Сыгран')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournament.tournamentpair', verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='tournament.tournament', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='beach_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж в пляжном волейболе'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='player',
            name='volleyball_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж в волейболе'),
        ),
        migrations.AlterField(
            model_name='setresult',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tournament.match', verbose_name='Матч'),
        ),
        migrations.AlterField(
            model_name='setresult',
            name='pair1_points',
            field=models.PositiveIntegerField(verbose_name='Очки пары 1'),
        ),
        migrations.AlterField(
            model_name='setresult',
            name='pair2_points',
            field=models.PositiveIntegerField(verbose_name='Очки пары 2'),
        ),
        migrations.AlterField(
            model_name='setresult',
            name='set_number',
            field=models.PositiveIntegerField(verbose_name='Номер партии'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format_type',
            field=models.CharField(choices=[('single_elim', 'Олимпийская система'), ('double_elim', 'До двух поражений'), ('round_robin', 'Круговая система')], max_length=30, verbose_name='Формат турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='tournamentgroup',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='tournamentgroup',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournament.tournament', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='tournamentpair',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_player1', to='tournament.player', verbose_name='Первый игрок'),
        ),
        migrations.AlterField(
            model_name='tournamentpair',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_player2', to='tournament.player', verbose_name='Второй игрок'),
        ),
        migrations.AlterField(
            model_name='tournamentpair',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='tournament.tournament', verbose_name='Турнир'),
        ),
        migrations.DeleteModel(
            name='PlayerTournamentHistory',
        ),
    ]
