# Generated by Django 6.0.4 on 2026-05-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_match_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='photo_album_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на фотоальбом'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
