# Generated by Django 6.0.4 on 2026-05-07 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournament_photo_album_link_tournament_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_stage',
            field=models.CharField(blank=True, choices=[('winners', 'Сетка победителей'), ('losers', 'Сетка проигравших'), ('final', 'Финал'), ('third_place', 'Матч за 3 место')], max_length=30, verbose_name='Часть сетки'),
        ),
        migrations.AddField(
            model_name='match',
            name='loser_next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser_previous_matches', to='tournament.match', verbose_name='Следующий матч для проигравшего'),
        ),
        migrations.AddField(
            model_name='match',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция в раунде'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Раунд сетки'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bracket_size',
            field=models.PositiveIntegerField(blank=True, choices=[(6, '6 команд'), (8, '8 команд'), (10, '10 команд'), (12, '12 команд'), (16, '16 команд'), (24, '24 команды'), (32, '32 команды')], null=True, verbose_name='Размер сетки'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format_type',
            field=models.CharField(choices=[('single_elim', 'Олимпийская система'), ('double_elim', 'До двух поражений')], max_length=30, verbose_name='Формат турнира'),
        ),
    ]
