# Generated by Django 6.0.4 on 2026-05-07 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_bracket_stage_match_loser_next_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pair1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pair1', to='tournament.tournamentpair', verbose_name='Пара 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='pair2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_pair2', to='tournament.tournamentpair', verbose_name='Пара 2'),
        ),
    ]
