# Generated by Django 6.0.5 on 2026-05-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_match_pair1_alter_match_pair2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bracket_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные сетки'),
        ),
    ]
