# Generated by Django 6.0.5 on 2026-05-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournament_bracket_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bracket_type',
        ),
        migrations.RemoveField(
            model_name='match',
            name='stage',
        ),
    ]
